name = "startest"
version = "0.2.3"
description = "A testing framework to help you shoot for the stars"
licenses = ["MIT"]
repository = { type = "github", user = "maxdeviant", repo = "startest" }

[dependencies]
argv = ">= 1.0.2 and < 2.0.0"
bigben = ">= 1.0.0 and < 2.0.0"
birl = ">= 1.6.1 and < 2.0.0"
exception = ">= 2.0.0 and < 3.0.0"
gleam_community_ansi = ">= 1.4.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_javascript = ">= 0.8.0 and < 1.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
glint = ">= 1.0.0-rc1 and < 1.0.0-rc2"
simplifile = ">= 1.7.0 and < 2.0.0"
tom = ">= 0.3.0 and < 1.0.0"

[dev-dependencies]
birdie = ">= 1.1.5 and < 2.0.0"
